### ISSUE TITLE
Link to documentation is broken 404

### ISSUE THREAD

**Issue by cnizzardini** [acmephp/ssl#14]
404: https://acmephp.github.io/acmephp/ssl/introduction.html

**Comment by fezfez** [comment]
Still broken!

**Comment by tgalopin** [comment]
I didn't notice that indeed, but I'm planning to remove the website documentation and migrate it under the main repository as MD files anyway (less maintenance requirement). In the meantime you can find the doc here: https://github.com/acmephp/documentation

**Comment by cnizzardini** [comment]
Might I recommend mkdocs: https://www.mkdocs.org/
